//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinAttributeProgrammer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinAttributeProgrammer.Resources.StringValues", typeof(StringValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Delay.
        /// </summary>
        public static string activDelay {
            get {
                return ResourceManager.GetString("activDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Curve Options.
        /// </summary>
        public static string advance {
            get {
                return ResourceManager.GetString("advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid adjusting values in this section unless it is required for the gauge to function properly..
        /// </summary>
        public static string attributeAdvanceWarning {
            get {
                return ResourceManager.GetString("attributeAdvanceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlight.
        /// </summary>
        public static string backlight {
            get {
                return ResourceManager.GetString("backlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlight Scan Rate.
        /// </summary>
        public static string BacklightScanRt {
            get {
                return ResourceManager.GetString("BacklightScanRt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLUE (.
        /// </summary>
        public static string blueSliderLbl {
            get {
                return ResourceManager.GetString("blueSliderLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** BETA MODE **
        ///This version is in beta mode for the purpose of testing and bug reports. Contents are subject to change. Please report any bug(s) you&apos;ve encountered via Contact option in the Advance page..
        /// </summary>
        public static string buildStageInfo {
            get {
                return ResourceManager.GetString("buildStageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to CLEAR ALL attribute values?.
        /// </summary>
        public static string clearAllAttWarning {
            get {
                return ResourceManager.GetString("clearAllAttWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the log? This action can not be reverted!.
        /// </summary>
        public static string clearLog {
            get {
                return ResourceManager.GetString("clearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand for Fine Tuning.
        /// </summary>
        public static string collapseSection {
            get {
                return ResourceManager.GetString("collapseSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the color of...
        /// </summary>
        public static string colorFocusLabel {
            get {
                return ResourceManager.GetString("colorFocusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCAN.
        /// </summary>
        public static string connectBtnTxt {
            get {
                return ResourceManager.GetString("connectBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTED.
        /// </summary>
        public static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial no: {0}
        ///Software Ver: {1}
        ///Board Type: {2}.
        /// </summary>
        public static string connectedInfoMsg {
            get {
                return ResourceManager.GetString("connectedInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device connected!.
        /// </summary>
        public static string connectedMsg {
            get {
                return ResourceManager.GetString("connectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect, could not establish a proper connection..
        /// </summary>
        public static string connectionFailed {
            get {
                return ResourceManager.GetString("connectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to the device..
        /// </summary>
        public static string connectionLost {
            get {
                return ResourceManager.GetString("connectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been copied to the clipboard..
        /// </summary>
        public static string copySuccess {
            get {
                return ResourceManager.GetString("copySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully renamed the gauge. The new name will appear after the gauge is restarted..
        /// </summary>
        public static string deviceRenamed {
            get {
                return ResourceManager.GetString("deviceRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully flashed gauge with updated firmware..
        /// </summary>
        public static string dfuSuccess {
            get {
                return ResourceManager.GetString("dfuSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimmer Voltage High.
        /// </summary>
        public static string dimVoltHi {
            get {
                return ResourceManager.GetString("dimVoltHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimmer Voltage Low.
        /// </summary>
        public static string dimVoltLo {
            get {
                return ResourceManager.GetString("dimVoltLo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not saved your changes. Leaving now will revert your changes, do you wish to continue?.
        /// </summary>
        public static string discardChangeMsg {
            get {
                return ResourceManager.GetString("discardChangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNLINK.
        /// </summary>
        public static string disconnectBtnTxt {
            get {
                return ResourceManager.GetString("disconnectBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT
        ///CONNECTED.
        /// </summary>
        public static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gauge is currently connected. Restart the gauge and start scanning to connect to your EV3!
        ///.
        /// </summary>
        public static string disconnectedInfoMsg {
            get {
                return ResourceManager.GetString("disconnectedInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Distance Units
        ///.
        /// </summary>
        public static string distanceUnits {
            get {
                return ResourceManager.GetString("distanceUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Driver.
        /// </summary>
        public static string driver {
            get {
                return ResourceManager.GetString("driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Accumulation.
        /// </summary>
        public static string enableAccumulation {
            get {
                return ResourceManager.GetString("enableAccumulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall Sensor.
        /// </summary>
        public static string enableSensor {
            get {
                return ResourceManager.GetString("enableSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Enabled .
        /// </summary>
        public static string enableTrip {
            get {
                return ResourceManager.GetString("enableTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not leave any empty fields..
        /// </summary>
        public static string errorEmptyField {
            get {
                return ResourceManager.GetString("errorEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving attribute to gauge. Try again.
        /// </summary>
        public static string errorMsg {
            get {
                return ResourceManager.GetString("errorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit using back button and return to update next device!.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string expand {
            get {
                return ResourceManager.GetString("expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to reset the attributes to factory defaults?.
        /// </summary>
        public static string factoryResetWarning {
            get {
                return ResourceManager.GetString("factoryResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Flashing.
        /// </summary>
        public static string flashBtn {
            get {
                return ResourceManager.GetString("flashBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting successfully saved to the gauge!.
        /// </summary>
        public static string flashedSuccessMsg {
            get {
                return ResourceManager.GetString("flashedSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Effect Value.
        /// </summary>
        public static string flashEffect {
            get {
                return ResourceManager.GetString("flashEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Intensity.
        /// </summary>
        public static string flashIntens {
            get {
                return ResourceManager.GetString("flashIntens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Zone.
        /// </summary>
        public static string flashZone {
            get {
                return ResourceManager.GetString("flashZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauge Mode.
        /// </summary>
        public static string gaugeMode {
            get {
                return ResourceManager.GetString("gaugeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauge Type.
        /// </summary>
        public static string gaugeType {
            get {
                return ResourceManager.GetString("gaugeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREEN (.
        /// </summary>
        public static string greenSliderLbl {
            get {
                return ResourceManager.GetString("greenSliderLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indication Zones.
        /// </summary>
        public static string indicationZone {
            get {
                return ResourceManager.GetString("indicationZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Accuulation (Miles or Hours).
        /// </summary>
        public static string lcdTotalAccumulation {
            get {
                return ResourceManager.GetString("lcdTotalAccumulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New gauge detected! Do you want to load the new gauge&apos;s attributes?.
        /// </summary>
        public static string loadNewGaugeAtt {
            get {
                return ResourceManager.GetString("loadNewGaugeAtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to load {0} attribute profile? The profile will not be saved into the gauge untill told so..
        /// </summary>
        public static string loadProfile {
            get {
                return ResourceManager.GetString("loadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string mini {
            get {
                return ResourceManager.GetString("mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needle.
        /// </summary>
        public static string needle {
            get {
                return ResourceManager.GetString("needle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices found..
        /// </summary>
        public static string nodevices {
            get {
                return ResourceManager.GetString("nodevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find TX and/or RX Characteristics..
        /// </summary>
        public static string noTXRXChar {
            get {
                return ResourceManager.GetString("noTXRXChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranmission channel does not allow write..
        /// </summary>
        public static string noWriteAccess {
            get {
                return ResourceManager.GetString("noWriteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown&gt;.
        /// </summary>
        public static string nullValue {
            get {
                return ResourceManager.GetString("nullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Value .
        /// </summary>
        public static string outputThres {
            get {
                return ResourceManager.GetString("outputThres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing the given input. Please enter a valid value!.
        /// </summary>
        public static string parseError {
            get {
                return ResourceManager.GetString("parseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please grant this app permission to your location always to use this feature..
        /// </summary>
        public static string permissionLocation {
            get {
                return ResourceManager.GetString("permissionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please grant this app permission to your location in order to use the BT feature..
        /// </summary>
        public static string permissionReqMsg {
            get {
                return ResourceManager.GetString("permissionReqMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Programmer collects location data to enable Bluetooth even when the app is closed or not in use..
        /// </summary>
        public static string permissionReqPrior {
            get {
                return ResourceManager.GetString("permissionReqPrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Required.
        /// </summary>
        public static string permissionTitle {
            get {
                return ResourceManager.GetString("permissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPR Precision.
        /// </summary>
        public static string precisionPPR {
            get {
                return ResourceManager.GetString("precisionPPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESETS.
        /// </summary>
        public static string presetLbl {
            get {
                return ResourceManager.GetString("presetLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer Weight.
        /// </summary>
        public static string ptrW8 {
            get {
                return ResourceManager.GetString("ptrW8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RED (.
        /// </summary>
        public static string redSliderLbl {
            get {
                return ResourceManager.GetString("redSliderLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string reload {
            get {
                return ResourceManager.GetString("reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard all changes that was made on this page to saved profile?.
        /// </summary>
        public static string resetMsg {
            get {
                return ResourceManager.GetString("resetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCANNING.
        /// </summary>
        public static string scanning {
            get {
                return ResourceManager.GetString("scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Coeff. 0.
        /// </summary>
        public static string sensCoeff0 {
            get {
                return ResourceManager.GetString("sensCoeff0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Coeff. 1.
        /// </summary>
        public static string sensCoeff1 {
            get {
                return ResourceManager.GetString("sensCoeff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Hysteresis.
        /// </summary>
        public static string sensHys {
            get {
                return ResourceManager.GetString("sensHys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Scan Rate.
        /// </summary>
        public static string sensScanRt {
            get {
                return ResourceManager.GetString("sensScanRt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedometer PPM.
        /// </summary>
        public static string speedoPPM {
            get {
                return ResourceManager.GetString("speedoPPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Settings.
        /// </summary>
        public static string speedoTachOutput {
            get {
                return ResourceManager.GetString("speedoTachOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedometer/Tachometer Settings.
        /// </summary>
        public static string speedtachSec {
            get {
                return ResourceManager.GetString("speedtachSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Delay.
        /// </summary>
        public static string startDelay {
            get {
                return ResourceManager.GetString("startDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucess.
        /// </summary>
        public static string successTitle {
            get {
                return ResourceManager.GetString("successTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachometer PPR.
        /// </summary>
        public static string tachPPR {
            get {
                return ResourceManager.GetString("tachPPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To .
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for DFU process to finish. .
        /// </summary>
        public static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Warning.
        /// </summary>
        public static string warnBtn {
            get {
                return ResourceManager.GetString("warnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Value Percentage.
        /// </summary>
        public static string warnThres {
            get {
                return ResourceManager.GetString("warnThres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
